### ISSUE TITLE
'Util is not defined' on rotate 

### ISSUE THREAD

**Issue by ivoba** [meltingice/CamanJS-Plugins#2]
I get this while trying to apply rotation filter: 

```
ReferenceError: Util is not defined
Util.copyAttributes(this.canvas, canvas);
```

what does it mean?

**Comment by ivoba** [comment]
I copied the compiled js into the main function of camanJS. 
then it works.  

I dont know coffeescript but i guess you have to import the plugins somehow and compile it together with the main part?

Some words on that would be helpful.

**Comment by xatzz** [comment]
I'm having the same problem and then copied the rotate method to the camanjs file and still have this problem.

**Comment by xatzz** [comment]
Nevermind, copied the rotate plugin next to the others filters and ir worked. Thanks ;)
